# Generated by Django 5.2 for WP-006.
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("drawings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name="ControlPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("spc_key", models.CharField(max_length=120)),
                (
                    "logical_code",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="control_points_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drawing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="control_points",
                        to="drawings.drawing",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="control_points_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ControlPointVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_no", models.PositiveIntegerField()),
                ("measure_code", models.CharField(max_length=120)),
                ("measure_name", models.CharField(max_length=255)),
                ("nominal", models.DecimalField(decimal_places=5, max_digits=14)),
                (
                    "lower_tolerance",
                    models.DecimalField(decimal_places=5, max_digits=14),
                ),
                (
                    "upper_tolerance",
                    models.DecimalField(decimal_places=5, max_digits=14),
                ),
                ("lower_limit", models.DecimalField(decimal_places=5, max_digits=14)),
                ("upper_limit", models.DecimalField(decimal_places=5, max_digits=14)),
                ("unit", models.CharField(default="mm", max_length=32)),
                ("page_no", models.PositiveIntegerField()),
                ("x_ratio", models.DecimalField(decimal_places=6, max_digits=7)),
                ("y_ratio", models.DecimalField(decimal_places=6, max_digits=7)),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "measurement_group",
                    models.CharField(default="Genel", max_length=120),
                ),
                (
                    "sample_frequency",
                    models.CharField(default="Her Kontrol", max_length=120),
                ),
                ("is_critical", models.BooleanField(default=False)),
                ("sort_no", models.IntegerField(default=0)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("change_reason", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "control_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="control_points.controlpoint",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="control_point_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drawing_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="control_point_versions",
                        to="drawings.drawingrevision",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="control_point_versions_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("sort_no", "measure_code", "id")},
        ),
        migrations.AddConstraint(
            model_name="controlpointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version_no__gte", 1)), name="cpv_version_no_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="controlpointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("page_no__gte", 1)), name="cpv_page_no_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="controlpointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("x_ratio__gte", 0), ("x_ratio__lte", 1)),
                name="cpv_x_ratio_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="controlpointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("y_ratio__gte", 0), ("y_ratio__lte", 1)),
                name="cpv_y_ratio_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="controlpointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("lower_tolerance__lte", 0)),
                name="cpv_lower_tol_nonpositive",
            ),
        ),
        migrations.AddConstraint(
            model_name="controlpointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("upper_tolerance__gte", 0)),
                name="cpv_upper_tol_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="controlpointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("lower_limit__lte", models.F("nominal"))),
                name="cpv_lower_limit_lte_nominal",
            ),
        ),
        migrations.AddConstraint(
            model_name="controlpointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("upper_limit__gte", models.F("nominal"))),
                name="cpv_upper_limit_gte_nominal",
            ),
        ),
        migrations.AddConstraint(
            model_name="controlpointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="cpv_valid_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="controlpointversion",
            constraint=models.UniqueConstraint(
                fields=("control_point", "version_no"), name="cpv_point_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="controlpointversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("control_point", "drawing_revision"),
                name="cpv_one_active_per_revision",
            ),
        ),
    ]
