# Generated by Django 5.2.8 on 2026-08-26
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="FileObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[("FILESYSTEM", "Filesystem")],
                        default="FILESYSTEM",
                        max_length=24,
                    ),
                ),
                (
                    "storage_key",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                ("original_name", models.CharField(editable=False, max_length=255)),
                ("mime_type", models.CharField(editable=False, max_length=255)),
                ("size_bytes", models.PositiveBigIntegerField(editable=False)),
                (
                    "sha256",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator("^[0-9a-f]{64}$")
                        ],
                    ),
                ),
                (
                    "encryption_scheme",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("LEGACY_AES_GCM", "Legacy AES-GCM"),
                        ],
                        default="NONE",
                        editable=False,
                        max_length=32,
                    ),
                ),
                (
                    "encryption_key_version",
                    models.CharField(
                        blank=True, editable=False, max_length=32, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="core_file_objects_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_file_object",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("size_bytes__gt", 0)),
                        name="core_file_size_positive",
                    )
                ],
            },
        )
    ]
